### ISSUE TITLE
aqd not starting because of missing directory

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aquilon#23]
When starting aqd for the first time, it complains because it cannot write to /var/log/aquilon/aqd.log :

```
-bash-4.1# service aqd start
Starting aquilon broker: Traceback (most recent call last):
  File "/usr/bin/aqd.py", line 30, in <module>
    twistd.run()
  File "/usr/lib64/python2.6/site-packages/twisted/scripts/twistd.py", line 27, in run
    app.run(runApp, ServerOptions)
  File "/usr/lib64/python2.6/site-packages/twisted/application/app.py", line 652, in run
    runApp(config)
  File "/usr/lib64/python2.6/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib/python2.6/site-packages/aquilon/twisted_patches.py", line 172, in updated_application_run
    start=False)
  File "/usr/lib/python2.6/site-packages/aquilon/twisted_patches.py", line 116, in set_log_file
    log_file = logfile.LogFile.fromFullPath(logFile, rotateLength=0)
  File "/usr/lib64/python2.6/site-packages/twisted/python/logfile.py", line 48, in fromFullPath
    os.path.dirname(logPath), *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/twisted/python/logfile.py", line 161, in __init__
    BaseLogFile.__init__(self, name, directory, defaultMode)
  File "/usr/lib64/python2.6/site-packages/twisted/python/logfile.py", line 40, in __init__
    self._openFile()
  File "/usr/lib64/python2.6/site-packages/twisted/python/logfile.py", line 166, in _openFile
    BaseLogFile._openFile(self)
  File "/usr/lib64/python2.6/site-packages/twisted/python/logfile.py", line 75, in _openFile
    self._file = file(self.path, "w+", 1)
IOError: [Errno 2] No such file or directory: '/var/log/aquilon/aqd.log'
```

the folder should be created upon installation and writable by the "aquilon" user.

**Comment by stdweird** [comment]
or be dealt with by quattor, eg https://github.com/stdweird/quattor-SCDB-ugent/blob/master/cfg/non-grid/hpc/common/aquilon/config.pan

**Comment by JulienNauroy** [comment]
Thanks for showing me the Quattor configuration file, I didn't know there was one.
But if you don't install Aquilon through Quattor, you still have to create the directory manually and give it proper rights.

**Comment by jrha** [comment]
Indeed, the RPM should create it.
Thanks for documenting these issues, the RPM doesn't get tested very often!

**Comment by dzila** [comment]
Confirmed issue still present. Perhaps we could document it until it gets fixed.

**Comment by samary** [comment]
Same issue with `/var/run/aquilon` and owned by `aquilon` user. 
The problem with this one is this directory is deleted on reboot (/var/run is tmpfs on EL7).
I don't know how to bypass this issue.

**Comment by jrha** [comment]
In that case the broker should create it... @gombasg?

**Comment by jrha** [comment]
@gombasg points out that the init script (or systemd) should create the /var/run directory.

**Comment by jouvin** [comment]
March 17 workshop: @gombasg suggests that `/var/run/aquilon` should be created by init script.

**Comment by urbonegi** [comment]
Any plans adding this here? https://github.com/quattor/aquilon/blob/1ecf0200b8bfdf219a76eb5b8a206e97cf5c3921/etc/rc.d/init.d/aqd
Or anywhere else? @jouvin

**Comment by stdweird** [comment]
@urbonegi don't add logic to the init script; at somepoint it has to become a systemd unit. altough you can also do this in the unitfiles, it is better if there is a set of pan templates we can use that sets everything correctly (this is quattor afterall). and yes, you can bootstrap this 😉

**Comment by ned21** [comment]
Should we close this in favour of #43 then? The use of the quattor template is a workaround for now?
