### ISSUE TITLE
aquilon and aquilon-protocols compiled for different versions of Python

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/aquilon#24]
I'm opening a different ticket since the problem is not the same.

Upon starting aqd, I now have the following error message:

```
2015-04-17 11:22:16+0200 [-] Starting aqd version Unknown
2015-04-17 11:22:16+0200 [-] Traceback (most recent call last):
2015-04-17 11:22:16+0200 [-]   File "/usr/bin/aqd.py", line 30, in <module>
2015-04-17 11:22:16+0200 [-]     twistd.run()
2015-04-17 11:22:16+0200 [-]   File "/usr/lib64/python2.6/site-packages/twisted/scripts/twistd.py", line 27, in run
2015-04-17 11:22:16+0200 [-]     app.run(runApp, ServerOptions)
2015-04-17 11:22:16+0200 [-]   File "/usr/lib64/python2.6/site-packages/twisted/application/app.py", line 652, in run
2015-04-17 11:22:16+0200 [-]     runApp(config)
2015-04-17 11:22:16+0200 [-]   File "/usr/lib64/python2.6/site-packages/twisted/scripts/twistd.py", line 23, in runApp
2015-04-17 11:22:16+0200 [-]     _SomeApplicationRunner(config).run()
2015-04-17 11:22:16+0200 [-]   File "/usr/lib/python2.6/site-packages/aquilon/twisted_patches.py", line 176, in updated_application_run
2015-04-17 11:22:16+0200 [-]     self.application = self.createOrGetApplication()
2015-04-17 11:22:16+0200 [-]   File "/usr/lib64/python2.6/site-packages/twisted/application/app.py", line 446, in createOrGetApplication
2015-04-17 11:22:16+0200 [-]     ser = plg.makeService(self.config.subOptions)
2015-04-17 11:22:16+0200 [-]   File "/usr/lib/python2.6/site-packages/twisted/plugins/aqd.py", line 157, in makeService
2015-04-17 11:22:16+0200 [-]     registry = ResourcesCommandRegistry(restServer)
2015-04-17 11:22:16+0200 [-]   File "/usr/lib/python2.6/site-packages/aquilon/worker/resources.py", line 515, in __init__
2015-04-17 11:22:16+0200 [-]     super(ResourcesCommandRegistry, self).__init__()
2015-04-17 11:22:16+0200 [-]   File "/usr/lib/python2.6/site-packages/aquilon/worker/resources.py", line 405, in __init__
2015-04-17 11:22:16+0200 [-]     entry.add_format(format, style)
2015-04-17 11:22:16+0200 [-]   File "/usr/lib/python2.6/site-packages/aquilon/worker/resources.py", line 507, in add_format
2015-04-17 11:22:16+0200 [-]     meth(format, self.broker_command.command)
2015-04-17 11:22:16+0200 [-]   File "/usr/lib/python2.6/site-packages/aquilon/worker/formats/formatters.py", line 76, in config_proto
2015-04-17 11:22:16+0200 [-]     raise ProtocolError("Protocol %s: %s" % (module, err))
2015-04-17 11:22:16+0200 [-] aquilon.exceptions_.ProtocolError: Protocol aqdsystems_pb2: No module named aqdsystems_pb2
```

I've found aqdsystems_pb2.py, but in /usr/local/lib/python2.7/dist-packages and not in python2.6.

Is there a problem related to python versions between aquilon modules? Is there a workarount?

**Comment by jrha** [comment]
Did you install the protocols from the RPM, because I think that puts them in the correct location for the system the RPM was built on.

AFAIK installing the protocols from the GitHub repo should put them in the correct place.

**Comment by jrha** [comment]
On our broker that module is in `/usr/local/lib/aquilon/protocols/lib/python/aqdsystems_pb2.py`

**Comment by samary** [comment]
There is a problem with the python version of aquilon RPMs: 
- `aquilon-protocols-1.10-1.noarch.rpm` is built against python2.7
- `aquilon-1.11.24_rc1-1.noarch.rpm` is built against python2.6

I had to recompile the aquilon-protocols rpm to match the correct python version (2.6 for CentOS 6) : 
- yum install protobuf-compiler rpmdevtools
- git clone https://github.com/quattor/aquilon-protocols
- cd protocols
- ./setup.py bdist_rpm
- yum install dist/aquilon-protocols-1.10-1.noarch.rpm

**Comment by JulienNauroy** [comment]
Samary's trick works fine, here are the next errors I've met and their solutions:
-  `aquilon.exceptions_.ProtocolError: Protocol aqdsystems_pb2: No module named google.protobuf` => yum install protobuf-python (must be added as a dependency)
- `IOError: [Errno 2] No such file or directory: '/var/run/aquilon/aqd.pid'` => create the directory (must be done by the RPM)
- `IOError: [Errno 2] No such file or directory: '/var/quattor/logs/aq_notifyd.log'` => also create this directory

Now I'm stuck with another error related to kerberos (knc not found). I'll see if this is a problem on my side before opening an issue.

**Comment by samary** [comment]
For KNC, you'll need the 'knc' rpm (`yum install knc`)
Then, in your `aqd.conf` add in the [kerberos] section : 
`knc = /usr/local/bin/knc`
`klist = /usr/bin/klist`

Hope it helps

Cheers

**Comment by JulienNauroy** [comment]
Thanks, it helped a lot, changing `aqd.conf` dit the job (knc was already installed as a dependency of one of the RPMs).

**Comment by ned21** [comment]
This should be fixed by https://github.com/quattor/release/pull/275. Please re-open if still an issue.
