### ISSUE TITLE
aquilon rpm installation throws an error

### ISSUE THREAD

**Issue by samary** [quattor/aquilon#47]
On the rpm installation of the `aquilon` rpm, the following error is thrown:
```
  Installing : aquilon-1.12.17_rc2-1.el7.noarch                                                                                                                      151/153 
Unhandled Error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    
  File "/usr/lib64/python2.7/site-packages/twisted/plugin.py", line 209, in getPlugins
    allDropins = getCache(package)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/plugin.py", line 167, in getCache
    provider = pluginModule.load()
  File "/usr/lib64/python2.7/site-packages/twisted/python/modules.py", line 383, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib64/python2.7/site-packages/twisted/python/reflect.py", line 506, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/usr/lib/python2.7/site-packages/twisted/plugins/aqd.py", line 33, in <module>
    from aquilon.worker.knc_protocol import KNCSite
  File "/usr/lib/python2.7/site-packages/aquilon/worker/knc_protocol.py", line 20, in <module>
    from twisted.web import http
exceptions.ImportError: No module named web
  Installing : aquilon-postgresql-1.0.0-1.noarch    
```

**Comment by stdweird** [comment]
`python-twisted-web` should be separate dependency in the setup.py or setup.cfg

**Comment by urbonegi** [comment]
@stdweird  If this fixed after linked PRs were merged?

**Comment by jrha** [comment]
`python-twisted-web` is listed as a dependency (see #48).
