### ISSUE TITLE
Experiment with building and running aqd in Docker

### ISSUE THREAD

**Issue by ned21** [quattor/aquilon#55]
Being able to ship aqd with its dependencies in a Docker container may be easier than making rpms for all the dependencies.

One challenge to overcome would be how to make the client available to users - that would probably still need to be an rpm.

**Comment by stdweird** [comment]
@ned21 i can understand that it might be easier to start or try out, but if we can't figure out how to package aquilon with rpms, i'm probably not going to touch it unless there is a nice and well tested upgrade and HA guide.

**Comment by ned21** [comment]
@stdweird Agree you wouldn't want to upgrade from rpms to Docker in the near future. The plan is to try and use Docker to help us understand our dependencies better and track when we change them. We may be moving towards a Docker-like system internally so it may be easier for us to maintain and validate than rpms.

One of the first issues I've hit is the need for some things like compiled protocols, which I'll probably work around by grabbing them from quattor externals!

**Comment by stdweird** [comment]
@ned21 i have little doubt that we can make rpms for aquilon and all its deps. we do way much more complicated stuff in quattor and some of our inhouse tools 😀

**Comment by ned21** [comment]
I decided to have another go at this with the aim of making it possible to run the test suite on travis. I had some success configuring a centos7 container following the [install instructions](https://www.quattor.org/aquilon/00-install.html) but the unit tests are failing because klist and kinit fails with: `klist: UID in persistent keyring name while getting default ccache`

This page provides and explanation: https://blog.tomecek.net/post/kerberos-in-a-container/ 
The solution is ~~probably to provide fake/mocked klist and kinit commands.~~ to ensure credentials are stored in a temporary file instead of kernel keyring: `export KRB5CCNAME=FILE:/tmp/tgt`

**Comment by ned21** [comment]
Adding an `ENV KRB5CCNAME` line to Dockerfile gets me a bit further:

```
% docker run --hostname test.example.com --rm --name aqd aquilon
Traceback (most recent call last):
  File "tests/../bin/aqd_config.py", line 43, in <module>
    from six.moves.configparser import NoSectionError, NoOptionError  # pylint: disable=F0401
ImportError: No module named six.moves.configparser
Failed to determine the base directory
```

Inside the container I get a different error:
```
% docker run -i -t --name aqd --rm aquilon /bin/bash -c "/bin/bash"            
[root@28f8574654f9 aquilon]# . /var/quattor/aquilon-venv/bin/activate 
(aquilon) [root@28f8574654f9 aquilon]# tests/dev_aqd.sh 

Using AQDCONF = /etc/aqd.conf
where basedir = /var
  and rundir  = /var/quattor/run
  and dsn     = sqlite:////var/quattor/aquilondb/aquilon.db

2019-11-08 19:59:02+0000 [-] Log opened.
2019-11-08 19:59:02+0000 [-] twistd 18.4.0 (/var/quattor/aquilon-venv/bin/python 2.7.5) starting up.
2019-11-08 19:59:02+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2019-11-08 19:59:02+0000 [-] Broker started with aqd symlink, setting config mode to readwrite
2019-11-08 19:59:02+0000 [-] Loading broker in mode readwrite
2019-11-08 19:59:03+0000 [-] Error importing aquilon.worker.formats.feature: Traceback (most recent call last):
	  File "/aquilon/sbin/../lib/aquilon/worker/formats/__init__.py", line 35, in <module>
	    mymodule = __import__(modulename, fromlist=["BrokerCommand"])
	  File "/aquilon/sbin/../lib/aquilon/worker/formats/feature.py", line 19, in <module>
	    from aquilon.worker.formats.formatters import ObjectFormatter
	  File "/aquilon/sbin/../lib/aquilon/worker/formats/formatters.py", line 30, in <module>
	    from aquilon.worker.processes import build_mako_lookup
	  File "/aquilon/sbin/../lib/aquilon/worker/processes.py", line 58, in <module>
	    import ms.version
	ImportError: No module named ms.version

```
